name: Deploy to github npm packages

on:
  push:
    tags:
      - 'v*-freshmile*'

env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          registry-url: https://npm.pkg.github.com/
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.14
      - run: bun install --frozen-lockfile
      - run: bun publish --dry-run
